name: voyage
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences:
  http:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  flutter_vector_icons: ^2.0.0
  font_awesome_flutter: ^10.6.0
  snippet_coder_utils: ^1.0.15
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  firebase_database: ^10.3.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - images/gallerie.png
    - images/profil.png
    - images/clear.png
    - images/clouds.png
    - images/contact.png
    - images/deconnexion.png
    - images/meteo.png
    - images/parametres.png
    - images/pays.png
    - images/rain.png
    - images/snow.png
